using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;

namespace Cell.Blazor.Internal.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScriptModules
    {
        [EnumMember(Value = "accumulationchart")] AccumulationChart,
        [EnumMember(Value = "base")] Base,
        [EnumMember(Value = "bulletchart")] BulletChart,
        [EnumMember(Value = "calendar")] Calendar,
        [EnumMember(Value = "datepicker")] DatePicker,
        [EnumMember(Value = "daterangepicker")] DateRangePicker,
        [EnumMember(Value = "datetimepicker")] DateTimePicker,
        [EnumMember(Value = "timepicker")] Timepicker,
        [EnumMember(Value = "chart")] Chart,
        [EnumMember(Value = "circulargauge")] CircularGauge,
        [EnumMember(Value = "compression")] Compression,
        [EnumMember(Value = "data")] DataManager,
        [EnumMember(Value = "documenteditor")] DocumentEditor,
        [EnumMember(Value = "drawings")] Drawings,
        [EnumMember(Value = "dropdownsbase")] DropDownBase,
        [EnumMember(Value = "dropdownlist")] DropDownList,
        [EnumMember(Value = "autocomplete")] AutoComplete,
        [EnumMember(Value = "combobox")] ComboBox,
        [EnumMember(Value = "multiselect")] MultiSelect,
        [EnumMember(Value = "excelexport")] ExcelExport,
        [EnumMember(Value = "filemanager")] FileManager,
        [EnumMember(Value = "fileutils")] FileUtils,
        [EnumMember(Value = "gantt")] Gantt,
        [EnumMember(Value = "heatmap")] Heatmap,
        [EnumMember(Value = "inplaceeditor")] InplaceEditor,
        [EnumMember(Value = "inputsbase")] InputBase,
        [EnumMember(Value = "splitter")] Splitter,
        [EnumMember(Value = "formvalidator")] FormValidator,
        [EnumMember(Value = "textbox")] TextBox,
        [EnumMember(Value = "numerictextbox")] NumericTextBox,
        [EnumMember(Value = "maskedtextbox")] MaskedTextBox,
        [EnumMember(Value = "uploader")] Uploader,
        [EnumMember(Value = "kanban")] Kanban,
        [EnumMember(Value = "lineargauge")] LinearGauge,
        [EnumMember(Value = "maps")] Maps,
        [EnumMember(Value = "officechart")] OfficeChart,
        [EnumMember(Value = "pdfexport")] PdfExport,
        [EnumMember(Value = "pdfviewer")] PdfViewer,
        [EnumMember(Value = "pivotview")] PivotView,
        [EnumMember(Value = "progressbar")] Progressbar,
        [EnumMember(Value = "querybuilder")] QueryBuilder,
        [EnumMember(Value = "rangenavigator")] RangeNavigator,
        [EnumMember(Value = "richtexteditor")] RichTextEditor,
        [EnumMember(Value = "schedule")] Schedule,
        [EnumMember(Value = "smithchart")] SmithChart,
        [EnumMember(Value = "sparkline")] Sparkline,
        [EnumMember(Value = "stockchart")] StockChart,
        [EnumMember(Value = "svgbase")] SvgBase,
        [EnumMember(Value = "treegrid")] TreeGrid,
        [EnumMember(Value = "treeview")] TreeView,
        [EnumMember(Value = "sidebar")] Sidebar,
        [EnumMember(Value = "grid")] Grid,
        [EnumMember(Value = "pager")] Pager,
        [EnumMember(Value = "popupsbase")] PopupsBase,
        [EnumMember(Value = "popup")] Popup,
        [EnumMember(Value = "toolbar")] Toolbar,
        [EnumMember(Value = "tab")] Tab,
        [EnumMember(Value = "accordion")] Accordion,
        [EnumMember(Value = "listview")] ListView,
        [EnumMember(Value = "listsbase")] ListBase,
        [EnumMember(Value = "buttonsbase")] ButtonBase,
        [EnumMember(Value = "colorpicker")] ColorPicker,
        [EnumMember(Value = "dropdownbutton")] DropDownButton,
        [EnumMember(Value = "button")] Button,
        [EnumMember(Value = "checkbox")] CheckBox,
        [EnumMember(Value = "radiobutton")] RadioButton,
        [EnumMember(Value = "switch")] Switch,
        [EnumMember(Value = "contextmenu")] ContextMenu,
        [EnumMember(Value = "menu")] Menu,
        [EnumMember(Value = "navigationsbase")] NavigationsBase,
        [EnumMember(Value = "splitbuttonsbase")] SplitbuttonsBase,
        [EnumMember(Value = "progressbutton")] ProgressButton,
        [EnumMember(Value = "splitbutton")] SplitButton,
        [EnumMember(Value = "listbox")] ListBox,
        [EnumMember(Value = "tooltip")] Tooltip,
        [EnumMember(Value = "dashboardlayout")] DashboardLayout,
        [EnumMember(Value = "chips")] Chips,
        [EnumMember(Value = "slider")] Slider,
        [EnumMember(Value = "diagrams")] Diagram,
        [EnumMember(Value = "symbolpalette")] SymbolPalette,
        [EnumMember(Value = "overview")] Overview,
        [EnumMember(Value = "dialog")] Dialog,
        [EnumMember(Value = "spinner")] Spinner,
        [EnumMember(Value = "cell-svg-export")] CellSvgExport,
        [EnumMember(Value = "sortable")] Sortable,
    }
}